version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ppi
      POSTGRES_PASSWORD: 6fCcDapDvg3uYc6bD8aeY8qTmjfVQ1vX
      POSTGRES_DB: ppi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
